### ISSUE TITLE
Improve to customize Details/Close text

### ISSUE THREAD

**Issue by davidcantonnadales** [myaasiinh/expandable_cardview#1]
Hello friend, congratulations for this widget, I love it.

Could you implement an improvement to be able to customize the Details and Close text?

Thanks!

![image](https://github.com/myaasiinh/expandable_cardview/assets/20184508/11dbf30f-12f9-438d-b584-19bd4b0e2e37)

**Comment by myaasiinh** [comment]
Of course, I will add this idea and update the next version release

**Comment by myaasiinh** [comment]
> Hello friend, congratulations for this widget, I love it.
> 
> Could you implement an improvement to be able to customize the Details and Close text?
> 
> Thanks!
> 
> ![image](https://private-user-images.githubusercontent.com/20184508/311536172-11dbf30f-12f9-438d-b584-19bd4b0e2e37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTE5NzEsIm5iZiI6MTcyNjY1MTY3MSwicGF0aCI6Ii8yMDE4NDUwOC8zMTE1MzYxNzItMTFkYmYzMGYtMTJmOS00MzhkLWI1ODQtMTliZDRiMGUyZTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA5Mjc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZmM3NDY2Y2FmNTIyOGFmMTczMjNjZmNlNzkzZTRiMzIzY2I3ZDQ0ZTVkZmUzZjIwMzE1NjcxMzNiNDliZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jNjE4Gl6Ct3hJNmGfUaQgxVh-vMy4mZV6W_zJSyq2nQ)

Alright this has been updated in next release 
![image](https://github.com/user-attachments/assets/221e418d-4b37-490f-9bc3-69758b3669c8)

![image](https://github.com/user-attachments/assets/ce5f1f8a-36ec-4c64-aaf9-184a89ac4393)
